from pathlib import Path

TILE_SIZE = 48
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

MAP_PATH = Path(__file__).with_name("map.txt")
TEXTURES_DIR = Path(__file__).with_name("textures")
SOUNDS_DIR = Path(__file__).with_name("sounds")
LEVELS_PATH = Path(__file__).with_name("levels.json")
NOTES_PATH = Path(__file__).with_name("notes.json")
CURRENT_LEVEL = 1
LEVEL_COUNT = 7
TILE_FLOOR = 1
TILE_WALL = 2
TILE_WALL_TOP = 3
TILE_FURNACE = 4
TILE_SPAWN = 6

ITEM_COAL = "coal"
ITEM_CANDLE = "candle"
ITEM_APPLE = "apple"
ITEM_LEVER = "lever"
ITEM_STONE = "stone"
ITEM_NOTE = "note"

ITEM_DRAW_SCALE = 0.6
ITEM_OUTLINE_COLOR = (80, 140, 200)
ITEM_MIN_DISTANCE_TILES = 25
ITEM_SPAWN_SAMPLES = 14
ITEM_SPAWN_ATTEMPTS = 120

MENU_BG = (12, 12, 16)
MENU_TEXT = (230, 230, 230)
MENU_ACCENT = (120, 180, 255)
MENU_DIM = (120, 120, 140)
MENU_LOCKED = (35, 75, 150)
MENU_LOCKED_DIM = (25, 55, 110)
MENU_LOCKED_TEXT = (220, 50, 50)

INTRO_BG = (0, 0, 0)
INTRO_TEXT = (230, 230, 230)
INTRO_MONSTER = (200, 60, 60)
INTRO_CHAR_RATE = 42

HUD_TEXT = (230, 230, 230)
HUD_SHADOW = (20, 20, 20)

DARK_TILE_FRACTION = 0.18
DARK_SAFE_RADIUS = 4
DARK_OVERLAY_ALPHA = 220
DARK_BLOB_COUNT = 2
DARK_BLOB_MIN_SIZE = 30
DARK_NOISE_OCTAVES = 3
DARK_NOISE_SCALE = 6
DARK_NOISE_PERSISTENCE = 0.55
DARK_SMOOTH_PASSES = 2
CANDLE_LIGHT_RADIUS = 1
SHADOW_BLUR_PASSES = 3
SHADOW_CORNER_RADIUS = 14
SHADOW_PAD = 8

AMBIENT_VOLUME = 0.35
CHASE_VOLUME = 0.55
SFX_VOLUME = 0.7
FOOTSTEP_VOLUME = 0.45
MUSIC_FADE_MS = 800
FOOTSTEP_FADE_MS = 120

SPOTLIGHT_RADIUS = 40
SPOTLIGHT_FEATHER = 0
SPOTLIGHT_ALPHA = 190
SPOTLIGHT_PULSE_SPEED = 2.0
SPOTLIGHT_PULSE_AMOUNT = 0.06
PLAYER_LIGHT_ALPHA = 135
CANDLE_LIGHT_ALPHA = 115
CANDLE_PULSE_SPEED = 4.5
CANDLE_PULSE_AMOUNT = 0.12
DUST_COUNT = 80
DUST_SPEED = 6
DUST_MAX_ALPHA = 30
DUST_MIN_SIZE = 1
DUST_MAX_SIZE = 2

MONSTER_SMELL_INTERVAL = 5.0
MONSTER_SMELL_RANGE_TILES = 10
MONSTER_SMELL_SPEED = 200
MONSTER_PASSIVE_SPEED = 100
MONSTER_HEARING_RANGE_TILES = 20
MONSTER_STOP_DISTANCE = 8
MONSTER_HEAD_SCALE = 1.4
MONSTER_ARM_UPPER_SCALE_X = 1.7
MONSTER_ARM_UPPER_SCALE_Y = 0.35
MONSTER_ARM_LOWER_SCALE_X = 1.8
MONSTER_ARM_LOWER_SCALE_Y = 0.5
MONSTER_SPAWN_SAFE_RADIUS = 20
MONSTER_SPAWN_MIN_DISTANCE = 10
MONSTER_PATROL_COUNT = 14
MONSTER_PATROL_SAMPLE_SIZE = 200
MONSTER_GRAB_RADIUS_TILES = 4
MONSTER_KILL_RADIUS = 36
MONSTER_STEP_SPEED = 1.6
MONSTER_GRAB_SWAY = 0.06
MONSTER_VISION_MEMORY = 4.0
MONSTER_ANCHOR_LERP = 0.08
MONSTER_TINT = (70, 70, 70)
CAMERA_ZOOM = 1.1

STONE_THROW_SPEED = 520

FREEZE_ENABLED = True
COLD_MAX = 100.0
COLD_RATE = 14.0
COLD_RECOVERY_RATE = COLD_RATE / 2

HUNGER_ENABLED = True
HUNGER_MAX = 100.0
HUNGER_RATE = 1.5
HUNGER_RESTORE = HUNGER_MAX / 2

SOLID_TILES = {0, TILE_WALL, TILE_WALL_TOP, TILE_FURNACE}
PLAYER_SPEED = 220
PLAYER_ANIM_INTERVAL = 0.18
